name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: |
          find storage bootstrap/cache -type d -exec chmod 755 {} \;
          find storage bootstrap/cache -type f -exec chmod 644 {} \;

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

  deploy:
    needs: laravel-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Beget
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          ARGS: "-avz --delete --exclude='.env' --exclude='storage/' --exclude='vendor/'"
          SOURCE: "."
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TARGET: ${{ secrets.REMOTE_DIR }}
          
      - name: Update Composer Dependencies on Production
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.REMOTE_USER }}
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd ${{ secrets.REMOTE_DIR }} && composer install --no-dev --optimize-autoloader
